package com.github.capntrips.kernelflasher.ui.theme

import androidx.compose.ui.graphics.Color

val Orange500 = Color(0xFFFF9800)

// Warm amber palette used when dynamic color is unavailable (Android < 12)
val LightPrimary = Color(0xFF8B5000)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDCBE)
val LightOnPrimaryContainer = Color(0xFF2C1600)
val LightSecondary = Color(0xFF725A42)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDCBE)
val LightOnSecondaryContainer = Color(0xFF291806)
val LightTertiary = Color(0xFF58633A)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDCE8B4)
val LightOnTertiaryContainer = Color(0xFF161E01)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFF8F5)
val LightOnBackground = Color(0xFF221A14)
val LightSurfaceVariant = Color(0xFFF3DFD1)
val LightOnSurfaceVariant = Color(0xFF52443A)
val LightOutline = Color(0xFF847469)
val LightOutlineVariant = Color(0xFFD7C3B6)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFFF1E8)
val LightSurfaceContainer = Color(0xFFF6EAE2)
val LightSurfaceContainerHigh = Color(0xFFF0E4DC)
val LightSurfaceContainerHighest = Color(0xFFEBDED6)
val LightInverseSurface = Color(0xFF382E28)
val LightInverseOnSurface = Color(0xFFFFEEE2)
val LightInversePrimary = Color(0xFFFFB870)

val DarkPrimary = Color(0xFFFFB870)
val DarkOnPrimary = Color(0xFF4A2800)
val DarkPrimaryContainer = Color(0xFF693C00)
val DarkOnPrimaryContainer = Color(0xFFFFDCBE)
val DarkSecondary = Color(0xFFE1C1A4)
val DarkOnSecondary = Color(0xFF402C18)
val DarkSecondaryContainer = Color(0xFF59422C)
val DarkOnSecondaryContainer = Color(0xFFFFDCBE)
val DarkTertiary = Color(0xFFC0CC9A)
val DarkOnTertiary = Color(0xFF2A3310)
val DarkTertiaryContainer = Color(0xFF404A24)
val DarkOnTertiaryContainer = Color(0xFFDCE8B4)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF19120C)
val DarkOnBackground = Color(0xFFEFE0D5)
val DarkSurfaceVariant = Color(0xFF52443A)
val DarkOnSurfaceVariant = Color(0xFFD7C3B6)
val DarkOutline = Color(0xFF9F8D81)
val DarkOutlineVariant = Color(0xFF52443A)
val DarkSurfaceContainerLowest = Color(0xFF130D07)
val DarkSurfaceContainerLow = Color(0xFF221A14)
val DarkSurfaceContainer = Color(0xFF261E18)
val DarkSurfaceContainerHigh = Color(0xFF312822)
val DarkSurfaceContainerHighest = Color(0xFF3C332C)
val DarkInverseSurface = Color(0xFFEFE0D5)
val DarkInverseOnSurface = Color(0xFF382E28)
val DarkInversePrimary = Color(0xFF8B5000)
