name: Android Build
permissions:
  contents: write
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew 
          ./gradlew assembleRelease
          tree app/build/outputs/apk/release

      - uses: r0adkll/sign-android-release@v1.0.4
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Rename APK
        run: |
          ls -al app/build/outputs/apk/release
          echo "Signed APK: ${{steps.sign_app.outputs.signedReleaseFile}}"
          cp ${{steps.sign_app.outputs.signedReleaseFile}} KernelFlasher.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.5
        with:
          name: KernelFlasher
          path: KernelFlasher.apk

      - name: Rename apk
        run: |
          ls -al
          DATE=$(date +'%y.%m.%d')
          echo "TAG=$DATE" >> $GITHUB_ENV

#      - name: Upload release
#        uses: ncipollo/release-action@v1.14.0
#        with:
#          allowUpdates: true
#          removeArtifacts: true
#          name: "1.${{ github.run_number }}.0"
#          tag: "v1.${{ github.run_number }}.0"
#          body: |
#            Note: QMod KernelFlasher, support ksu-lkm
#          artifacts: "*.apk"